### ISSUE TITLE
abstract base class bug?

### ISSUE THREAD

**Issue by waynenilsen** [williame/obiwan#7]
I have a minimal working example of this bug in python 3.4

```python

import abc
from obiwan import *; install_obiwan_runtime_check()

class Foo(metaclass=abc.ABCMeta):
	
	@abc.abstractmethod
	def bar(self):
		pass
		
class FooImpl(Foo):
	def bar(self):
		print('hi')

def do_stuff_with_a_foo_implementation(f: [Foo]):
	f.bar()

do_stuff_with_a_foo_implementation([FooImpl()])
	
```

I'm not sure what it is about the list that causes the trouble but it is required. It works fine without the list 

Console dump:
```
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\obiwan\__init__.py", line 281, in duckable

    if not isinstance(obj, collections.abc.Sequence):
AttributeError: 'module' object has no attribute 'abc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "obiwan_abc_test.py", line 17, in <module>
    do_stuff_with_a_foo_implementation([FooImpl()])
  File "obiwan_abc_test.py", line 14, in do_stuff_with_a_foo_implementation
    def do_stuff_with_a_foo_implementation(f: [Foo]):
  File "C:\Python34\lib\site-packages\obiwan\__init__.py", line 401, in _runtime
_checker
    duckable(arg, constraint, "%s(%s)" % (frame.f_code.co_name, key))
  File "C:\Python34\lib\site-packages\obiwan\__init__.py", line 318, in duckable

    raise ObiwanError("%s internal error: %s" % (ctx, e))
obiwan.ObiwanError: do_stuff_with_a_foo_implementation(f) internal error: 'modul
e' object has no attribute 'abc'
```

**Comment by williame** [comment]
You are using Python 3.4?  I'm guessing so, from the C:\Python34 in the path.

However, you do not seem to have [collections.abc](https://docs.python.org/3/library/collections.abc.html) which was added in Python 3.4.

What does your `python --version` say?

I do not have windows myself, but I can suggest a tentative fix along these lines:

At the top of obiwan/__init__.py
    try:
       import abc
    except ImportError:
       try:
         import collections.abc as abc
       except ImportError:
         error message here

and then later where we check this isinstance it would be `if not isinstance(obj, abc.Sequence)`

**Comment by waynenilsen** [comment]
You raise an interesting point which is essentially that my first example was in no way minimal. Initially, I thought it was because *I* was using `abc` but in fact it's just due to the use of list type verification. In my environment (exact version is 3.4.3) list type does not work. New minimal example below

```python
from obiwan import *; install_obiwan_runtime_check()

def foo(f: [int]):
	return f

foo([2])
```

gives

```
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\obiwan\__init__.py", line 281, in duckable
    if not isinstance(obj, collections.abc.Sequence):
AttributeError: 'module' object has no attribute 'abc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "obiwan_abc_test_2.py", line 6, in <module>
    foo([2])
  File "obiwan_abc_test_2.py", line 3, in foo
    def foo(f: [int]):
  File "C:\Python34\lib\site-packages\obiwan\__init__.py", line 401, in _runtime_checker
    duckable(arg, constraint, "%s(%s)" % (frame.f_code.co_name, key))
  File "C:\Python34\lib\site-packages\obiwan\__init__.py", line 318, in duckable
    raise ObiwanError("%s internal error: %s" % (ctx, e))
obiwan.ObiwanError: foo(f) internal error: 'module' object has no attribute 'abc'
```

I think the bug is introduced on [line 9](https://github.com/williame/obiwan/blob/master/obiwan/__init__.py#L9) of init which should maybe be `import collections.abc` since `abc` is a submodule of `collections` it cannot be used directly. For example, the code below fails

```
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import collections
>>> collections.abc.Sequence
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'abc'
```

I will make a PR to this effect.

**Comment by williame** [comment]
Aha we were slayed by https://bugs.python.org/issue20784

Thx for the fix
